import { test, after } from 'node:test';
import assert from 'node:assert/strict';
import { Pool } from 'pg';
import { pool, withTenant } from '../src/lib/db';
import { createCustomer, getCustomer, getActivity } from '../src/lib/customers';
import { customerSchema } from '../src/lib/validation';
import { hashPassword, verifyPassword } from '../src/lib/password';
const org='10000000-0000-4000-8000-000000000001';
const other='10000000-0000-4000-8000-000000000002';
const actor={id:'20000000-0000-4000-8000-000000000001',organizationId:org,role:'admin' as const};
const input={name:'ملف اختبار آلي اصطناعي',entityType:'company',country:'AE'};
const admin=new Pool({connectionString:process.env.DATABASE_ADMIN_URL});
const created:string[]=[];
after(async()=>{for(const id of created){await admin.query('DELETE FROM audit_events WHERE customer_id=$1',[id]);await admin.query('DELETE FROM customers WHERE id=$1',[id]);}await Promise.all([pool.end(),admin.end()]);});
test('password hashing is salted and rejects wrong passwords',()=>{const a=hashPassword('test-password');assert.notEqual(a,hashPassword('test-password'));assert.equal(verifyPassword('test-password',a),true);assert.equal(verifyPassword('wrong',a),false);});
test('invalid customer fields rejected; forged risk stripped',()=>{assert.equal(customerSchema.safeParse({...input,email:'bad'}).success,false);assert.equal(customerSchema.safeParse({...input,name:' '}).success,false);assert.equal('risk_level' in customerSchema.parse({...input,risk_level:'low'}),false);});
test('app role cannot bypass RLS and no tenant context reveals no rows',async()=>{const r=await pool.query('SELECT rolbypassrls,rolsuper FROM pg_roles WHERE rolname=current_user');assert.deepEqual(r.rows[0],{rolbypassrls:false,rolsuper:false});assert.equal((await pool.query('SELECT id FROM customers')).rowCount,0);});
test('create persists draft plus audit and second organization cannot read it',async()=>{const {id}=await createCustomer(actor,input);created.push(id);const c=await getCustomer(org,id);assert.equal(c?.screening_status,'not_run');assert.equal(c?.risk_level,'unassessed');assert.equal(c?.status,'draft');assert.equal(await getCustomer(other,id),null);assert.equal((await getActivity(org,id))[0].action,'customer.created');assert.equal((await getActivity(other,id)).length,0);});
test('RLS denies foreign organization write even without application filters',async()=>{await assert.rejects(withTenant(org,db=>db.query("INSERT INTO customers(organization_id,reference,name,entity_type,country,created_by) VALUES($1,'TEST-DENIED','اختبار','company','AE',$2)",[other,actor.id])),/row-level security/);});
test('transaction context does not leak after success or rollback',async()=>{await withTenant(org,db=>db.query('SELECT id FROM customers'));assert.equal((await pool.query('SELECT id FROM customers')).rowCount,0);await assert.rejects(withTenant(org,async()=>{throw Error('rollback-test');}));assert.equal((await pool.query('SELECT id FROM customers')).rowCount,0);});
test('viewer cannot create and app cannot alter audit history',async()=>{await assert.rejects(createCustomer({...actor,role:'viewer'},input),/FORBIDDEN/);await assert.rejects(withTenant(org,db=>db.query("UPDATE audit_events SET summary='changed'")),/permission denied/);});
test('audit failure rolls back customer write',async()=>{let id='';await assert.rejects(withTenant(org,async db=>{const r=await db.query("INSERT INTO customers(organization_id,reference,name,entity_type,country,created_by) VALUES($1,'TEST-ROLLBACK','اختبار','company','AE',$2) RETURNING id",[org,actor.id]);id=r.rows[0].id;await db.query("INSERT INTO audit_events(organization_id,actor_id,customer_id,action,summary) VALUES($1,$2,$3,'test',NULL)",[org,actor.id,id]);}));assert.equal(await getCustomer(org,id),null);});
