import { chromium } from '/Users/ahmed/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright/index.mjs';
import assert from 'node:assert/strict';
import { mkdir } from 'node:fs/promises';
await mkdir('docs/evidence/screenshots',{recursive:true});
const browser=await chromium.launch({headless:true,channel:"chrome"});
const page=await browser.newPage({viewport:{width:1440,height:1100}});
const testName='شركة اختبار الواجهة الاصطناعية '+Date.now();
const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.goto('http://127.0.0.1:3000/login');
await page.screenshot({path:'docs/evidence/screenshots/login.png',fullPage:true});
await page.getByRole('button',{name:'الدخول إلى مساحة العمل'}).click();
await page.waitForURL('http://127.0.0.1:3000/');
await page.screenshot({path:'docs/evidence/screenshots/dashboard.png',fullPage:true});
await page.getByRole('link',{name:'إضافة عميل'}).click();
await page.getByLabel('الاسم القانوني الكامل').fill(testName);
await page.getByRole('button',{name:'حفظ ملف العميل'}).click();
await page.waitForURL(/profiles\/.+\?created=1/);
const saved=page.url();
assert.ok(await page.getByRole('heading',{name:testName}).isVisible());
await page.reload();
assert.ok(await page.getByRole('heading',{name:testName}).isVisible());
await page.getByRole('button',{name:'تسجيل الخروج'}).click();
await page.waitForURL('**/login');
await page.getByRole('button',{name:'مكتب البيان',exact:true}).click();
await page.getByRole('button',{name:'الدخول إلى مساحة العمل'}).click();
await page.waitForURL('http://127.0.0.1:3000/');
await page.goto(saved);
assert.ok(await page.getByRole('heading',{name:'الملف غير متاح'}).isVisible());
await page.goto('http://127.0.0.1:3000/');
await page.getByRole('button',{name:'تسجيل الخروج'}).click();
await page.waitForURL('**/login');
await page.getByRole('button',{name:'مدقق للقراءة',exact:true}).click();
await page.getByRole('button',{name:'الدخول إلى مساحة العمل'}).click();
await page.waitForURL('http://127.0.0.1:3000/');
assert.equal(await page.getByRole('link',{name:'إضافة عميل'}).count(),0);
await page.goto('http://127.0.0.1:3000/profiles/new');
assert.ok((await page.textContent('body')).includes('قراءة'));
await page.goto('http://127.0.0.1:3000/profiles?q='+encodeURIComponent(testName));
assert.equal(await page.locator('tbody tr').count(),1);
await page.goto('http://127.0.0.1:3000/sources');
await page.screenshot({path:'docs/evidence/screenshots/sources.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.goto('http://127.0.0.1:3000/');
assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
await page.screenshot({path:'docs/evidence/screenshots/mobile.png',fullPage:true});
assert.deepEqual(errors,[]);
console.log('PASS: login, persisted customer, tenant denial, viewer permissions, search, sources, mobile overflow, no page errors.');
await browser.close();
